stages:
    - build
    - deploy

build-back:
    stage: build
    only : 
        - master 
        - develop
    script:
        - cd $CI_PROJECT_DIR/backend
        - chmod +x mvnw
        - ./mvnw package
        - cp target/*.jar ~/app1.jar
    tags :
        # !! tag 값이 동일하게 설정된 Runner만 파이프라인을 동작시킴
        # 여러 서버에 배포할때 서버별 runner 태그로도 활용(dev, stg, prd)
        - i3c202

build-front:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - frontend/node_modules
    only : 
        - master 
        - develop
    script:
        - cd $CI_PROJECT_DIR/desgin
        - npm install
        - npm run build
        - rm -rf /home/ubuntu/devCloud/s03p13c202/desgin/dist
        - cp -rf dist /home/ubuntu/devCloud/s03p13c202/desgin
    tags :
        - i3c202

deploy-back:
    stage: deploy
    only : 
        - master 
        - develop
    script :
        - cd $HOME
        - /home/ubuntu/restart_backend1.sh
    tags :
        - i3c202

deploy-front:
    stage: deploy
    only : 
        - master
        - develop
    script :
        - ls -al /home/ubuntu/devCloud/s03p13c202/desgin/dist
    tags :
        - i3c202